import './globals.css';
import localFont from 'next/font/local';
import Link from 'next/link';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });
// const avara = localFont({
//   src: './fonts/Avara-Bold.woff',
//   variable: '--font-avara',
//   weight: '500',
// });
const sligoil = localFont({
  src: './fonts/SligoilMicro.woff',
  variable: '--font-sligoil',
  weight: '500',
});

const basteleurMoonlight = localFont({
  src: './fonts/Basteleur-Moonlight.woff2',
  variable: '--font-basteleurM',
  weight: '300',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${sligoil.variable}`}
        className={basteleurMoonlight.variable}
      >
        {/* <header>
          <nav>
            <Link href="/fs-map-tone">FS Map Tone</Link>
            <Link href="/register">Register</Link>
            <Link href="/login">Login</Link>
          </nav>
        </header> */}
        {children}
      </body>
    </html>
  );
}
